### ISSUE TITLE
running ./viki configure gives error

### ISSUE THREAD

**Issue by sonyccd** [UT-RAM/viki#13]
```
./viki: line 6: 
VIKI: more than a GUI for ROS, https://github.com/UT-RAM/viki 
version: 0.2 - Alice
copyright: Robin Hoogervorst, Alex Kamphuis, Cees Trouwborst, 2016 
licensed under the MIT License
: No such file or directory
./viki: line 12: $'\n    Entry point for the VIKI command line,\n    parses the arguments and uses a mapping to execute the right stuff\n': command not found
./viki: line 14: import: command not found
from: can't read /var/mail/core.cli
./viki: line 17: syntax error near unexpected token `('
./viki: line 17: `parser = argparse.ArgumentParser()'
```

**Comment by robin9975** [comment]
Thanks for the feedback!

Apparently, something went wrong during the release, making the file fail. To fix this, it involves two steps:
1. Move the #/usr/bin/python (line 8) line in the viki file to the top
2. Add a 'config.json' file to the root directory of viki, which includes '{}' (without the quotes)

I will fix this and create a pull-request for this after the weekend.

**Comment by sonyccd** [comment]
Now this.
```

Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Traceback (most recent call last):
  File "./viki", line 38, in <module>
    run_functions[args.method](args.options)
  File "/home/brad/viki/core/cli/runnables.py", line 53, in configure
    subprocess.call(command)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by robin9975** [comment]
Hey, sorry for the terribly late response. I hope to do some more extensive testing on a clean machine this weekend, since I can't clearly figure out what the problem is. 

Did you add the 'config.json' file (step 2 in my previous comment)?

**Comment by robin9975** [comment]
Okay, this should now be fixed with the upper merge.

If you still have any problems, you might try:

- For now, I seem also to have some problems using the zsh shell, instead of bash. So try using bash, since that's the shell we tested it for. I think it's even ROS that doesn't like the zsh shell, since it loads .bash files
- Make sure you have rospack installed (can be installed using apt-get (ros-<version>-rospack)) 
- Make sure you have rosdep installed and initialized

Could you confirm if the bug has been resolved?
